namespace KeelMatrix.CliContract.Core;

// This is the independently authored source-schema contract used by the
// projection coverage guard. It intentionally does not reference the
// descriptor catalog: the observed side must come from serialized output.
internal static class SourceContractExpectedFields
{
    public static IReadOnlySet<string> Fields { get; } = new HashSet<string>(
    [
        "root.opencliVersion",
        "root.info.title",
        "root.info.summary",
        "root.info.description",
        "root.info.binary",
        "root.info.version",
        "root.info.license.name",
        "root.info.license.spdxId",
        "root.info.license.url",
        "root.info.contact.name",
        "root.info.contact.email",
        "root.info.contact.url",
        "root.install[].name",
        "root.install[].command",
        "root.install[].url",
        "root.install[].description",
        "root.global.config.json",
        "root.global.config.toml",
        "root.global.config.yaml",
        "root.global.exitCodes[].code",
        "root.global.exitCodes[].status",
        "root.global.exitCodes[].summary",
        "root.global.exitCodes[].description",
        "root.global.flags[].name",
        "root.global.flags[].aliases",
        "root.global.flags[].summary",
        "root.global.flags[].description",
        "root.global.flags[].type",
        "root.global.flags[].required",
        "root.global.flags[].variadic",
        "root.global.flags[].minItems",
        "root.global.flags[].maxItems",
        "root.global.flags[].hint",
        "root.global.flags[].hidden",
        "root.global.flags[].default",
        "root.global.flags[].choices[].value",
        "root.global.flags[].choices[].description",
        "root.global.flags[].alternativeSources[].type",
        "root.global.flags[].alternativeSources[].property",
        "root.commands.*.aliases",
        "root.commands.*.summary",
        "root.commands.*.description",
        "root.commands.*.hidden",
        "root.commands.*.kind",
        "root.commands.*.exitCodes[].code",
        "root.commands.*.exitCodes[].status",
        "root.commands.*.exitCodes[].summary",
        "root.commands.*.exitCodes[].description",
        "root.commands.*.examples[].title",
        "root.commands.*.examples[].content",
        "root.commands.*.args[].name",
        "root.commands.*.args[].summary",
        "root.commands.*.args[].description",
        "root.commands.*.args[].type",
        "root.commands.*.args[].required",
        "root.commands.*.args[].variadic",
        "root.commands.*.args[].minItems",
        "root.commands.*.args[].maxItems",
        "root.commands.*.args[].passthrough",
        "root.commands.*.args[].choices[].value",
        "root.commands.*.args[].choices[].description",
        "root.commands.*.flags[].name",
        "root.commands.*.flags[].aliases",
        "root.commands.*.flags[].summary",
        "root.commands.*.flags[].description",
        "root.commands.*.flags[].type",
        "root.commands.*.flags[].required",
        "root.commands.*.flags[].variadic",
        "root.commands.*.flags[].minItems",
        "root.commands.*.flags[].maxItems",
        "root.commands.*.flags[].hint",
        "root.commands.*.flags[].hidden",
        "root.commands.*.flags[].default",
        "root.commands.*.flags[].choices[].value",
        "root.commands.*.flags[].choices[].description",
        "root.commands.*.flags[].alternativeSources[].type",
        "root.commands.*.flags[].alternativeSources[].property"
    ], StringComparer.Ordinal);
}
